---

# Check var is defined :
#

- debug: var=hostvars[inventory_hostname]


- fail: msg="Variable '{{ item }}' is not defined"
  when: item not in vars
  with_items: 
    - sv_program_name
    - sv_user_name
    - sv_command
    - sv_umask
    - sv_autostart
    - sv_autorestart
    - sv_stderr_logfile
    - sv_stdout_logfile
    - sv_environment
    - sv_log_dir